# Generated by Django 5.2.1 on 2025-06-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockMarketNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField()),
                ("banner_image", models.URLField()),
                ("authors", models.CharField(max_length=200)),
                ("time_published", models.DateTimeField()),
                ("source", models.CharField(max_length=200)),
                ("overall_sentiment_label", models.CharField(max_length=200)),
                ("overall_sentiment_score", models.FloatField()),
                ("url", models.URLField()),
            ],
            options={
                "verbose_name": "Stock Market News",
                "verbose_name_plural": "Stock Market News",
                "ordering": ["-time_published"],
            },
        ),
    ]
