# Generated by Django 5.2.1 on 2025-06-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stockmarket_news", "0002_alter_stockmarketnews_authors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmarketnews",
            name="authors",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="stockmarketnews",
            name="overall_sentiment_label",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="stockmarketnews",
            name="source",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="stockmarketnews",
            name="title",
            field=models.CharField(max_length=10000),
        ),
    ]
