# Generated by Django 5.2.1 on 2025-06-04 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stockmarket_news", "0004_alter_stockmarketnews_banner_image_and_more"),
    ]

    operations = []
