# Generated by Django 5.2.1 on 2025-06-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stockmarket_news", "0005_auto_20250604_1436"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmarketnews",
            name="banner_image",
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
    ]
