# Generated by Django 5.2.1 on 2025-06-05 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stockmarket_news", "0006_alter_stockmarketnews_banner_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockmarketnews",
            options={
                "verbose_name": "Stock Market News",
                "verbose_name_plural": "Stock Market News",
            },
        ),
    ]
