# Generated by Django 5.2.1 on 2025-06-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockMarketData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_symbol", models.CharField(max_length=100)),
                ("from_date", models.DateTimeField()),
                ("after_hours", models.FloatField()),
                ("at_close", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("at_open", models.FloatField()),
                ("pre_market", models.FloatField()),
                ("status", models.CharField(max_length=100)),
                ("volume", models.FloatField()),
                ("otc", models.BooleanField()),
                ("sma", models.FloatField()),
                ("ema", models.FloatField()),
                ("macd", models.FloatField()),
                ("rsi", models.FloatField()),
            ],
        ),
    ]
