# Generated by Django 5.1.7 on 2025-06-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stockmarket_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmarketdata",
            name="otc",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
