# Generated by Django 5.2.1 on 2025-06-11 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stockmarket_data", "0002_alter_stockmarketdata_otc"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stock_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stockmarket_data.stockmarketdata",
                    ),
                ),
            ],
        ),
    ]
